language: java
jdk:
- oraclejdk7
- openjdk7
- oraclejdk8
env:
  global:
  - FTP_USER="khazaddum.caltech.edu|futuristicmaterials"
  - secure: SkwHcjTon/FHXVQKa8dtPaNwVnsZkiVkRwWBuKM1X8y02vhngqA0BCDfVErWfZG5FrmXnPRXahvC7C7/vwWSd4QERopEcP/grL1BKx8BkOsyP2bUDcjw5az2N34k2ffUp1PbSmWFJNf7qocxGQCYUsntw79N3LcZX7iTwNHhfVVykisyq6UUdIf7eUs9pdZ8xFiyeP9lPWlsy102xDI6r3STh94Gd/3q7vp+IHHI7HTZkhZmtJti/bl55E3ekDfWWw/MfjE3VWZ9dwtTQ4qF0foXZFr6Qc60HgbilxfT+O9SmjkPda7VemGD/42gQ4gqNbcJcTj4EVyDS3Y7ubJmWnvtbJikVZmeF9/p53c0tXQv2cyg9GSZGSHKiG6ngFSPcusAq7/VmHHV3ffSNQYzr478vnwlrbeG/Epmgos56uYPLRxeHUVF9ozBHYWDpZMXqrJXKpHPrAyj0RPSbe2tk1USI00/nli28CveeLjsRLjFzG2cmfSBwRVWfzs/r5hv+QthKs87l255G9RkF5IalGaiAbhcCeg9+2RdWasW1dxO4+EItaFvDgMTCdzNG8louRO92Gc4xxHhHWbyLK+uiNg4E3XnNtBrI1O/Ph73vRkrBs0xvY6qUV4fEab5qfGZIdzXia6BWJ1IQkyCCSpHrLBwHJn3tz0mV2GFnxEkOM8=
before_install:
- chmod +x gradlew
before_deploy:
- echo "deploying ${RELEASE_FILE} to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: ajZISnhsB/3N+0hDhZlx/ipS1/M7+0kJQpPZPXg4z2tnlv7sfYT2DheUiR1IOiLHpSB7+Fkm0oprh3UQvJhNJeL3W+ADe9VORcaBAmRXVSNF0pWV/VAgDnAFcuFes3fDnDiDzus09aOBhbN5rqcNoltQagOejAFUK6ECY26JVIGexe5Oy+IvqfDiSXvgj6FdXy/BmYHn8nwyu9+lIhJDj7WoptD5SqGJ0c0vH/XItCjHmP0ejttuACkS/Iy9oFW8aEtJNSHsMZJ9khlQY1/cF9oSMSYiOwKdiv4iCNtbNO3r2QZNS9llNUBnb9yFVd2TJhB2DUOS9gw5mQJA5UI+KZG+vs3LR9zsrv6aiErNtxGa39hctiMR/a5uezIMldiyEzYaIJU6qAu0f/3onJFEiGNwUz5YQPeJCSDsvmuZJvTUJ3WIxEuv2DHrJaoEjpgmRS6EZqtkSCzyieo9EK1LNfixB6EHKci4h0n2PxP9sF+RVS+KnbJzHcLKHwBftdQEgHiN2SPD6BU1a52gmvP2NhYv5ysfM42chtLmY8BesLGaKTdZLpjDJkkytlJstFh7td8TDJ29tLmRZi/Yu/9IXue8MfAWH9wYNH4LqfS4iAIha4PTybGNLc379IHy3QsJijCaIZhDZ5W5/+59rtWYpkOBxkGWdCXt3iiHOhuS+70=
  file: "${RELEASE_FILE}"
  on:
    repo: TheNumenorean/FuturisticMaterials
    branch: MC1.7
    tags: true
    jdk: oraclejdk7
after_success:
- export RELEASE_FILE=$(ls build/libs/*.jar)
- curl --ftp-ssl -3 -k --ftp-create-dirs -T ${RELEASE_FILE} --user $FTP_USER:$FTP_PASSWORD ftp://khazaddum.caltech.edu/futuristicmaterials/files/${RELEASE_FILE:11:-4}.${TRAVIS_BUILD_NUMBER}-${TRAVIS_BRANCH}.jar
